In [1]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of the variables list_ and array_list. The list_ variable is a regular
Python list, while the array_list variable is a NumPy array.'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types of both variables
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))


Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


In [2]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.'''

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print data types of each element in num_list
print("Data types of elements in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

# Print data types of each element in num_array
print("\nData types of elements in num_array:")
for row in num_array:
    for element in row:
        print(type(element))



Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
arr1 = num_array.shape
arr2 = num_array.size
print(arr1)
print(arr2)




(2, 3)
6


In [7]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]'''

import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''

import numpy as np
identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
